### ISSUE TITLE
Hranice Karatsuba

### ISSUE THREAD

**Issue by HalfDeadPie** [robertek/mi-pap#1]
Dobrý deň, chcel by som sa spýtať akym sposobom ste prišli na hranice FOR cyklu v Karatsuba algoritme. To znamená ako by sa dalo vysvetliť, kde má vnútorný FOR cyklus začať a kde skončiť. Ďakujem.

**Comment by robertek** [comment]
Uz jsem to nevidel 5 let. Ale letmy pohled do kodu napovida ze hranice vyplyvaji z` p+q<i` a `p>q>=0`. Takze si staci precist komentar pred funkci calculate_C. Nebo si nakreslit jak ten vzorec vypada a co dela.

Viz https://github.com/robertek/mi-pap/blob/master/doc/pap.pdf
a https://en.wikipedia.org/wiki/Karatsuba_algorithm
